#!/bin/bash

# Desarrollar un algoritmo que solicite al usuario dos números y muestre el resultado de la 
# suma de esos números por pantalla. Repetir esta operación mientras que el usuario así lo disponga.

while :
do
	declare -i number1=0
	read -p "Numero: " number1
	
	declare -i number2=0
	read -p "Numero: " number2

	echo "La suma es $((number1 + number2))"

	read -p "Otra suma? (s/n): " another

	[ $another == "s" ] || break
done

exit 0
