#!/bin/bash

# Desarrollar un algoritmo que lea números de forma indefinida hasta que se ingrese un cero.
# Mostrar la suma de todos los números ingresados.

declare -i total=0

while :
do
	declare -i number=0
	read -p "Numero: " number

	total=$((total + number))

	((number != 0)) || break
done

echo "Total: $total"

exit 0
