#!/bin/bash

# Desarrollar una calculadora que realice suma, resta, multiplicación, división y potencia. Repetir hasta que el usuario
# decida salir. Utilizar funciones.

. functionLibrary6

while : 
do
	result=0

	clear

	read -p "Número: " number1
	read -p "Operación (s, r, m, d, p): " operation
	read -p "Número: " number2

	case $operation in
		s) 
			result=$(add $number1 $number2)
			;;
		r) 
			result=$(substract $number1 $number2)
			;;
		m)
			result=$(multiply $number1 $number2)
			;;
		d)
			result=$(divide $number1 $number2)
			;;
		p)
			result=$(pow $number1 $number2)
			;;
		*)
			echo "Opción incorrecta"
			;;
	esac

	echo
	echo "Resultado: $result"
	echo

	read -p "Realizar otro cálculo? (s/n): " repeat

	[ $repeat == "s" ] || break
done

exit 0
