#!/bin/bash

# Crear una función que reciba un número y lo devuelva elevado al cubo. 

function pow3() {
	local number=$1
	
	echo $((number * number * number))
}

read -p "Número: " number

echo "$number al cubo es: $(pow3 $number)"

exit 0
