#!/bin/bash

. mainMenu
. createMenu
. searchMenu
. loadSave

loadData

currentIndex=${#status[@]}

while :
do
	mainMenu

	read -p "Seleccione una opción: " mainOption

	case $mainOption in
		a | A)
			create
			;;
		b | B)
			search
			;;
		s | S)
			echo
			echo "Gracias!"
			echo
			;;
		*)
			echo
			echo "ERROR! OPCION INCORRECTA"
			sleep 1
	esac

	[[ $mainOption != "s" && $mainOption != "S" ]] || break
done

saveData 

exit 0
