#!/bin/bash

declare -i -r SIZE=1000
declare -i -a vector=()
declare -i i=0
declare -i j=0
declare -i auxiliary=0

for ((i = 0; i < SIZE; i++)) {
	vector[i]=$((RANDOM % SIZE))
}

SECONDS=0

for ((i = 0; i < SIZE -1; i++)) {

	for (( j = i + 1; j < SIZE; j++)) {
		if ((vector[i] > vector[j]))
		then
			auxiliary=${vector[i]}
			vector[i]=${vector[j]}
			vector[j]=$auxiliary
		fi
	}
}

declare -i elapsed_time=$SECONDS

for ((i = 0; i < SIZE; i++)) {
	echo ${vector[i]}
}

echo "Tiempo de ordenamiento: $elapsed_time"

exit 0
